spring.application.name=Team3-project-backend

spring.datasource.url=jdbc:mysql://localhost:3306/TRProject

spring.datasource.username=root
spring.datasource.password=Wani2884@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
